services:
    server:
        build: server
        ports:
          - "8080:8080"
    client:
        build: client
        depends_on:
          - server
        ports:
          - "8009:8009"
        links:
          - server
